import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[window]
option_as_alt = "Both"
blur = true
dynamic_padding = true

[window.dimensions]
columns = 168
lines = 51

[font]
size = 15

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Light"

[font.bold]
style = "Bold"

[keyboard]
bindings = [{key = "Return", mods = "Alt", action = "ToggleFullScreen" }]
