import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[window]
option_as_alt = "Both"
decorations = "Transparent"
blur = true
startup_mode = "Maximized"

[window.dimensions]
columns = 145
lines = 45

[window.padding]
x = 7
y = 26

[font]
size = 15

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Light"

[font.bold]
style = "Bold"
